import { useState } from 'react';
import { useStore } from '../../context/StoreContext';

export const AdminLoginPage = () => {
  const [ok, setOk] = useState(localStorage.getItem('aaj_admin') === '1');
  if (ok) return <div className="py-8"><a href="/admin/dashboard" className="text-gold">Go to Dashboard</a></div>;
  return <div className="py-8 max-w-md mx-auto premium-card p-4"><h1 className="section-title">Admin Login</h1><input id="u" placeholder="admin@aarohi.com" className="border p-2 rounded w-full my-2"/><input id="p" type="password" placeholder="••••••" className="border p-2 rounded w-full"/><button onClick={()=>{localStorage.setItem('aaj_admin','1');setOk(true);}} className="bg-charcoal text-white w-full mt-3 py-2 rounded">Login</button></div>;
};

export const AdminDashboard = () => {
  const { products, categories, orders, enquiries } = useStore();
  const revenue = orders.reduce((s,o)=>s+(o.total||0),0);
  const stats=[['Total products',products.length],['Total categories',categories.length],['Total orders',orders.length],['Pending orders',orders.filter(o=>o.status!=='Delivered').length],['Delivered orders',orders.filter(o=>o.status==='Delivered').length],['Total revenue',`₹${revenue}`],['Enquiries',enquiries.length],['New users',42]];
  return <div className="py-8"><h1 className="section-title mb-4">Admin Dashboard</h1><div className="grid md:grid-cols-4 gap-3">{stats.map(([k,v])=><div key={k} className="premium-card p-4"><p className="text-sm text-gray-500">{k}</p><p className="text-2xl font-semibold">{v}</p></div>)}</div></div>;
};

export const AdminProducts = () => {
  const { products, setProducts, categories } = useStore();
  const [form, setForm] = useState({name:'',category:categories[0]?.name||'',price:999,oldPrice:1299,description:'Premium handcrafted set',material:'Alloy',tags:'festival',stockQuantity:10,sku:'AAJ-NEW',featured:false,bestseller:false,newArrival:true,thumbnail:'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=600&q=80'});
  const add = () => setProducts([{...form,id:Date.now(),slug:form.name.toLowerCase().replace(/[^a-z0-9]+/g,'-'),discount:Math.round((form.oldPrice-form.price)/form.oldPrice*100),reviewCount:0,rating:0,images:[form.thumbnail],availability:'In Stock',shortDescription:form.description,shippingInfo:'Ships in 24-48 hrs',returnInfo:'7 day returns',careInstructions:'Keep dry',color:'Gold',style:'Traditional',occasion:'Festival',subcategory:form.category,collectionType:'New',tags:form.tags.split(',')},...products]);
  const del = (id) => setProducts(products.filter((p)=>p.id!==id));
  return <div className="py-8 grid lg:grid-cols-3 gap-4"><div className="premium-card p-4 space-y-2">{Object.entries(form).map(([k,v])=>typeof v==='boolean'?<label key={k} className="flex gap-2"><input type="checkbox" checked={v} onChange={(e)=>setForm({...form,[k]:e.target.checked})}/>{k}</label>:k==='category'?<select key={k} value={v} onChange={(e)=>setForm({...form,[k]:e.target.value})} className="border p-2 rounded w-full">{categories.map((c)=><option key={c.id||c.name}>{c.name}</option>)}</select>:<input key={k} value={v} onChange={(e)=>setForm({...form,[k]:e.target.value})} placeholder={k} className="border p-2 rounded w-full"/>)}<button onClick={add} className="w-full bg-charcoal text-white py-2 rounded">Save Product</button></div><div className="lg:col-span-2 space-y-2">{products.slice(0,20).map((p)=><div key={p.id} className="premium-card p-3 flex justify-between"><div>{p.name}<p className="text-xs">₹{p.price}</p></div><button onClick={()=>del(p.id)} className="text-red-500">Delete</button></div>)}</div></div>;
};

export const AdminCategories = () => { const {categories,setCategories}=useStore(); const [name,setName]=useState(''); return <div className="py-8"><h1 className="section-title mb-3">Manage Categories</h1><div className="premium-card p-4"><input value={name} onChange={(e)=>setName(e.target.value)} className="border p-2 rounded" placeholder="Category"/><button onClick={()=>{setCategories([...categories,{id:Date.now(),name,slug:name.toLowerCase()}]);setName('');}} className="ml-2 bg-charcoal text-white px-3 py-2 rounded">Add</button><div className="mt-3 flex flex-wrap gap-2">{categories.map((c)=><span key={c.id} className="bg-blush px-2 py-1 rounded text-sm">{c.name}</span>)}</div></div></div>; };
export const AdminOrders = () => { const {orders}=useStore(); return <div className="py-8"><h1 className="section-title mb-3">Manage Orders</h1>{orders.map((o)=><div key={o.id} className="premium-card p-3 mb-2">{o.id} - ₹{o.total} - {o.status}</div>)}{!orders.length&&<div className="premium-card p-3">No orders yet.</div>}</div>; };
export const AdminBanners = () => { const {banners,setBanners}=useStore(); const [title,setTitle]=useState(''); return <div className="py-8"><h1 className="section-title mb-3">Banner Management</h1><div className="premium-card p-4"><input value={title} onChange={(e)=>setTitle(e.target.value)} className="border p-2 rounded" placeholder="Banner title"/><button onClick={()=>{setBanners([...banners,{id:Date.now(),title,subtitle:'New banner',image:banners[0]?.image,cta:'Shop now'}]);setTitle('');}} className="ml-2 bg-charcoal text-white px-3 py-2 rounded">Add Banner</button></div></div>; };
export const AdminCustomers = () => { const {enquiries}=useStore(); return <div className="py-8"><h1 className="section-title mb-3">Enquiries</h1>{enquiries.map((e)=><div key={e.id} className="premium-card p-3 mb-2">{e.name} • {e.subject}</div>)}{!enquiries.length&&<div className="premium-card p-3">No enquiries yet.</div>}</div>; };
export const AdminCoupons = () => { const {coupons,setCoupons}=useStore(); const [code,setCode]=useState(''); return <div className="py-8"><h1 className="section-title mb-3">Coupon Management</h1><div className="premium-card p-4"><input value={code} onChange={(e)=>setCode(e.target.value)} className="border p-2 rounded" placeholder="Code"/><button onClick={()=>{setCoupons([...coupons,{code,type:'percent',value:10,active:true}]);setCode('');}} className="ml-2 bg-charcoal text-white px-3 py-2 rounded">Add Coupon</button><div className="mt-3">{coupons.map((c)=><span key={c.code} className="mr-2 text-sm">{c.code}</span>)}</div></div></div>; };
export const AdminReviews = () => <div className="py-8"><h1 className="section-title">Reviews Management</h1><div className="premium-card p-4">Review moderation placeholder.</div></div>;
export const AdminSettings = () => { const {settings,setSettings}=useStore(); return <div className="py-8"><h1 className="section-title mb-3">Store Settings</h1><div className="premium-card p-4 grid md:grid-cols-2 gap-2">{Object.entries(settings).map(([k,v])=><input key={k} value={v} onChange={(e)=>setSettings({...settings,[k]:e.target.value})} className="border p-2 rounded" placeholder={k}/>)}</div></div>; };
