import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { adminService, authService } from '../../lib/services';

const card = 'rounded-2xl border border-cyan-400/20 bg-white/10 backdrop-blur-lg shadow-[0_0_40px_rgba(20,184,166,0.15)] p-4';
const statusList = ['Pending', 'Confirmed', 'Packed', 'Dispatched', 'Delivered', 'Cancelled'];

export const AdminLoginPage = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const navigate = useNavigate();

  const login = async () => {
    try {
      setLoading(true);
      setError('');
      const data = await authService.signIn({ email, password });
      if (data.user?.role !== 'admin') throw new Error('Admin access required');
      navigate('/admin', { replace: true });
      window.location.reload();
    } catch (e) {
      setError(e.response?.data?.message || e.message || 'Login failed');
    } finally {
      setLoading(false);
    }
  };

  return <div className="py-8 max-w-md mx-auto"><div className={card}><h1 className="section-title">Admin Login</h1><input value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email" className="border p-2 rounded w-full my-2 bg-black/20"/><input value={password} onChange={(e) => setPassword(e.target.value)} type="password" placeholder="Password" className="border p-2 rounded w-full bg-black/20"/>{error && <p className="mt-2 text-sm text-rose-200">{error}</p>}<button disabled={loading} onClick={login} className="bg-charcoal text-white w-full mt-3 py-2 rounded disabled:opacity-70 disabled:cursor-not-allowed">{loading ? 'Authenticating...' : 'Login'}</button></div></div>;
};

export const AdminDashboard = () => {
  const [data, setData] = useState(null);
  useEffect(() => { adminService.getDashboard().then(setData); }, []);
  if (!data) return <div className="py-8">Loading analytics...</div>;
  const stats = [['Total sales', `₹${Math.round(data.totalSales)}`], ['Total orders', data.totalOrders], ['Pending', data.pendingOrders], ['Dispatched', data.dispatchedOrders], ['Delivered', data.deliveredOrders], ['Cancelled', data.cancelledOrders], ['Total products', data.totalProducts], ['Low stock', data.lowStockCount], ['Total users', data.totalUsers]];
  return <div className="py-8 space-y-4"><h1 className="section-title">Admin Dashboard</h1><div className="grid md:grid-cols-3 lg:grid-cols-5 gap-3">{stats.map(([k, v]) => <div key={k} className={card}><p className="text-sm text-cyan-100">{k}</p><p className="text-2xl font-semibold text-white">{v}</p></div>)}</div></div>;
};

export const AdminProducts = () => {
  const empty = { name: '', slug: '', description: '', category: '', brand: '', price: 0, salePrice: 0, stock: 0, sku: '', featured: false, isActive: true, thumbnail: null, galleryImages: [] };
  const [form, setForm] = useState(empty); const [rows, setRows] = useState([]); const [categories, setCategories] = useState([]); const [editingId, setEditingId] = useState('');
  const load = async () => { const [items, cats] = await Promise.all([adminService.listProducts(), adminService.listCategories()]); setRows(items || []); setCategories(cats || []); };
  useEffect(() => { load(); }, []);
  const uploadThumb = async (file) => { if (!file) return; const uploaded = await adminService.uploadSingle(file); setForm((prev) => ({ ...prev, thumbnail: uploaded })); };
  const save = async () => { if (editingId) await adminService.updateProduct(editingId, form); else await adminService.createProduct(form); setForm(empty); setEditingId(''); load(); };
  return <div className="py-8 grid lg:grid-cols-3 gap-4"><div className={`${card} space-y-2`}>{['name', 'slug', 'description', 'brand', 'price', 'salePrice', 'stock', 'sku'].map((k) => <input key={k} value={form[k] ?? ''} onChange={(e) => setForm({ ...form, [k]: ['price', 'salePrice', 'stock'].includes(k) ? Number(e.target.value) : e.target.value })} placeholder={k} className="border p-2 rounded w-full bg-black/20" />)}<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} className="border p-2 rounded w-full bg-black/20"><option value="">Category</option>{categories.map((c) => <option key={c._id} value={c.name}>{c.name}</option>)}</select><label className="flex gap-2"><input type="checkbox" checked={form.featured} onChange={(e) => setForm({ ...form, featured: e.target.checked })}/>featured</label><label className="flex gap-2"><input type="checkbox" checked={form.isActive} onChange={(e) => setForm({ ...form, isActive: e.target.checked })}/>active</label><input type="file" accept="image/*" onChange={(e) => uploadThumb(e.target.files?.[0])} className="border p-2 rounded w-full bg-black/20" />{form.thumbnail?.url && <img src={form.thumbnail.url} className="h-20 rounded"/>}<button onClick={save} className="w-full bg-charcoal text-white py-2 rounded">{editingId ? 'Update' : 'Create'} Product</button></div><div className="lg:col-span-2 space-y-2">{rows.map((p) => <div key={p._id} className={`${card} flex justify-between items-center`}><div className="flex items-center gap-3"><img src={p.thumbnail?.url} className="h-12 w-12 rounded object-cover"/><div><p>{p.name}</p><p className="text-xs">SKU:{p.sku} • Stock: <span className={p.stock <= 5 ? 'text-red-300' : 'text-emerald-300'}>{p.stock}</span></p></div></div><div className="space-x-2"><button onClick={() => { setEditingId(p._id); setForm(p); }} className="text-cyan-200">Edit</button><button onClick={async () => { if (window.confirm('Delete product?')) { await adminService.deleteProduct(p._id); load(); } }} className="text-red-300">Delete</button></div></div>)}</div></div>;
};

export const AdminOrders = () => { const [orders, setOrders] = useState([]); useEffect(() => { adminService.listOrders().then(setOrders); }, []); return <div className="py-8 space-y-3"><h1 className="section-title">Orders</h1>{orders.map((o) => <div key={o._id} className={card}><div className="flex justify-between"><div><p>#{o._id}</p><p className="text-xs">{o.user?.name} • {o.paymentMethod} • ₹{o.total}</p></div><select value={o.status} onChange={async (e) => { await adminService.updateOrderStatus(o._id, { status: e.target.value }); setOrders(await adminService.listOrders()); }} className="border p-2 rounded bg-black/20">{statusList.map((s) => <option key={s}>{s}</option>)}</select></div></div>)}</div>; };
export const AdminUsers = () => { const [users, setUsers] = useState([]); useEffect(() => { adminService.listUsers().then(setUsers); }, []); return <div className="py-8"><h1 className="section-title mb-3">Users</h1><div className={card}>{users.map((u) => <div key={u._id} className="border-b border-white/10 py-2 text-sm">{u.name} • {u.email} • {u.role}</div>)}</div></div>; };
export const AdminBanners = () => { const [rows, setRows] = useState([]); const [form, setForm] = useState({ title: '', subtitle: '', cta: 'Shop Now', link: '/shop', order: 0, active: true, image: null }); const load = async () => setRows(await adminService.listBanners()); useEffect(() => { load(); }, []); return <div className="py-8"><h1 className="section-title mb-3">Banners</h1><div className={card}><div className="grid md:grid-cols-5 gap-2">{['title', 'subtitle', 'cta', 'link'].map((k) => <input key={k} value={form[k]} onChange={(e) => setForm({ ...form, [k]: e.target.value })} placeholder={k} className="border p-2 rounded bg-black/20" />)}<input type="file" accept="image/*" onChange={async (e) => { const up = await adminService.uploadSingle(e.target.files?.[0]); setForm({ ...form, image: up }); }} className="border p-2 rounded bg-black/20"/></div><button onClick={async () => { await adminService.createBanner(form); load(); }} className="mt-2 bg-charcoal text-white px-3 py-2 rounded">Create banner</button></div><div className="mt-3 space-y-2">{rows.map((b) => <div key={b._id} className={`${card} flex justify-between items-center`}><div className="flex items-center gap-2"><img src={b.image?.url} className="h-12 w-20 object-cover rounded"/><span>{b.title}</span></div><button onClick={async () => { await adminService.deleteBanner(b._id); load(); }} className="text-red-300">Delete</button></div>)}</div></div>; };
export const AdminEnquiries = () => { const [rows, setRows] = useState([]); const load = async () => setRows(await adminService.listEnquiries()); useEffect(() => { load(); }, []); return <div className="py-8"><h1 className="section-title mb-3">Enquiries</h1><div className={card}>{rows.map((e) => <div key={e._id} className="flex justify-between border-b border-white/10 py-2"><span>{e.name} • {e.email} • {e.subject}</span><div className="space-x-2"><button onClick={async () => { await adminService.markEnquiry(e._id, !e.isRead); load(); }} className="text-cyan-200">Mark {e.isRead ? 'Unread' : 'Read'}</button><button onClick={async () => { await adminService.deleteEnquiry(e._id); load(); }} className="text-red-300">Delete</button></div></div>)}</div></div>; };
export const AdminCoupons = () => { const [rows, setRows] = useState([]); const [form, setForm] = useState({ code: '', type: 'percentage', value: 10, minOrderAmount: 0, expiry: '', active: true }); const load = async () => setRows(await adminService.listCoupons()); useEffect(() => { load(); }, []); return <div className="py-8"><h1 className="section-title mb-3">Coupons</h1><div className={card}><div className="grid md:grid-cols-6 gap-2"><input value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} placeholder="Code" className="border p-2 rounded bg-black/20"/><select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })} className="border p-2 rounded bg-black/20"><option value="percentage">Percentage</option><option value="fixed">Fixed</option></select><input type="number" value={form.value} onChange={(e) => setForm({ ...form, value: Number(e.target.value) })} placeholder="Value" className="border p-2 rounded bg-black/20"/><input type="number" value={form.minOrderAmount} onChange={(e) => setForm({ ...form, minOrderAmount: Number(e.target.value) })} placeholder="Min order" className="border p-2 rounded bg-black/20"/><input type="date" value={form.expiry} onChange={(e) => setForm({ ...form, expiry: e.target.value })} className="border p-2 rounded bg-black/20"/><button onClick={async () => { await adminService.createCoupon({ ...form, code: form.code.toUpperCase() }); load(); }} className="bg-charcoal text-white rounded">Create</button></div></div><div className="mt-2">{rows.map((c) => <div key={c._id} className={`${card} flex justify-between mb-2`}><span>{c.code} • {c.type} • {c.value}</span><button className="text-red-300" onClick={async () => { await adminService.deleteCoupon(c._id); load(); }}>Delete</button></div>)}</div></div>; };
export const AdminSettings = () => { const [form, setForm] = useState({}); useEffect(() => { adminService.getSettings().then(setForm); }, []); return <div className="py-8"><h1 className="section-title mb-3">Settings & Content</h1><div className={`${card} grid md:grid-cols-2 gap-2`}>{['storeName', 'homeText', 'aboutText', 'footerText', 'supportEmail', 'supportPhone'].map((k) => <input key={k} value={form[k] || ''} onChange={(e) => setForm({ ...form, [k]: e.target.value })} className="border p-2 rounded bg-black/20" placeholder={k} />)}<button onClick={async () => { await adminService.saveSettings(form); window.alert('Saved'); }} className="md:col-span-2 bg-charcoal text-white py-2 rounded">Save</button></div></div>; };
export const AdminCategories = () => { const [rows, setRows] = useState([]); const [form, setForm] = useState({ name: '', slug: '', image: '' }); const load = async () => setRows(await adminService.listCategories()); useEffect(() => { load(); }, []); return <div className="py-8"><h1 className="section-title mb-3">Categories</h1><div className={card}><div className="grid md:grid-cols-4 gap-2"><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Name" className="border p-2 rounded bg-black/20"/><input value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })} placeholder="Slug" className="border p-2 rounded bg-black/20"/><input value={form.image} onChange={(e) => setForm({ ...form, image: e.target.value })} placeholder="Image URL" className="border p-2 rounded bg-black/20"/><button onClick={async () => { await adminService.createCategory({ ...form, slug: form.slug || form.name.toLowerCase().replace(/[^a-z0-9]+/g, '-') }); setForm({ name: '', slug: '', image: '' }); load(); }} className="bg-charcoal text-white rounded">Create</button></div>{rows.map((c) => <div key={c._id} className="flex justify-between border-b border-white/10 py-2"><span>{c.name}</span><button onClick={async () => { await adminService.deleteCategory(c._id); load(); }} className="text-red-300">Delete</button></div>)}</div></div>; };
export const AdminReviews = () => <div className="py-8"><div className={card}>Reviews API endpoint available for extension.</div></div>;
export const AdminLogoutButton = () => { const navigate = useNavigate(); return <button onClick={() => { authService.signOut(); navigate('/admin/login'); window.location.reload(); }} className="bg-rose-700 text-white px-3 py-1 rounded">Logout</button>; };
